version: "{build}"
image:
  - Visual Studio 2017
  - Visual Studio 2019 Preview
platform:
  - Win32
  - x64
build_script:
  - git submodule update --init --recursive
  - scripts\build_all.bat
test: off
